"""
trim_to_40.py
1. Verifies all 40 real images are present on disk.
2. Deletes 110 unused cases/patients/predictions/consultations from local_db.json.
3. Deletes their synthetic CXR image files from dicoms/.
4. Clears old heatmaps and FAISS index (will be regenerated by batch_infer.py).
5. Runs batch inference on the 40 real images.

Run AFTER downloading all 34 images from download_urls.txt.
"""

import json
import shutil
import sys
from pathlib import Path

_BACKEND  = Path(__file__).resolve().parent
_REPO     = _BACKEND.parent
_DICOMS   = _REPO / "frontend" / "public" / "mock-data" / "dicoms"
_HEATMAPS = _REPO / "frontend" / "public" / "mock-data" / "heatmaps"
_DB_PATH  = _BACKEND / "local_db.json"

KEEP_SHORT_IDS = {
    "f1e3d197","ad58402a","2f54d7f5","813d610a","b5113ad5","238ecb55",
    "3b1950dc","2d15ff35","38186792","f7148544","e427a8fb","8343b48c",
    "ec4ee9ea","60b43b71","f0d86a7b","d71eef46","4abed709","a67377ff",
    "9c6b22f7","36fcd761","7d8ce05a","dbb0f050","7e31a8b0","bfbd4450",
    "27c45cfd","e4300324","df7bea55","4026462e","07afb995","e96d0a66",
    "aa25e1b2","88008c93","7eb0348b","f3597bf0","6c247d24","7e5f562d",
    "1ad15ac4","1845969f","d9dfe7a3","7037c41f",
}

def main():
    # ── Step 1: Verify all 40 images present ─────────────────────────────────
    print("Checking images...")
    missing = []
    for short in KEEP_SHORT_IDS:
        p = _DICOMS / f"case_{short}.png"
        if not p.exists():
            missing.append(short)

    if missing:
        print(f"\nMISSING {len(missing)} images — download them first:")
        for s in missing:
            print(f"  case_{s}.png")
        print("\nSee backend/download_urls.txt for the URLs.")
        sys.exit(1)

    print(f"All 40 images present. Proceeding with trim...")

    # ── Step 2: Trim local_db.json ────────────────────────────────────────────
    db = json.load(open(_DB_PATH))

    # Build keep sets
    keep_case_ids = {c["id"] for c in db["cases"] if c["id"][:8] in KEEP_SHORT_IDS}
    keep_patient_ids = {c["patient_id"] for c in db["cases"] if c["id"] in keep_case_ids}

    before_cases    = len(db["cases"])
    before_patients = len(db["patients"])
    before_preds    = len(db.get("predictions", []))

    db["cases"]       = [c for c in db["cases"]       if c["id"] in keep_case_ids]
    db["patients"]    = [p for p in db["patients"]    if p["id"] in keep_patient_ids]
    db["predictions"] = [p for p in db.get("predictions", []) if p["case_id"] in keep_case_ids]
    db["consultations"] = [c for c in db.get("consultations", []) if c.get("case_id") in keep_case_ids]

    with open(_DB_PATH, "w") as f:
        json.dump(db, f, indent=2)

    print(f"  Cases:       {before_cases} -> {len(db['cases'])}")
    print(f"  Patients:    {before_patients} -> {len(db['patients'])}")
    print(f"  Predictions: {before_preds} -> {len(db['predictions'])}")

    # ── Step 3: Delete unused synthetic CXR images ───────────────────────────
    deleted_imgs = 0
    for img in _DICOMS.glob("case_*.png"):
        short = img.stem.replace("case_", "")[:8]
        if short not in KEEP_SHORT_IDS:
            img.unlink()
            deleted_imgs += 1
    print(f"  Deleted {deleted_imgs} unused CXR images from dicoms/")

    # ── Step 4: Clear all old heatmaps ───────────────────────────────────────
    heatmap_count = 0
    for hm in _HEATMAPS.glob("*.png"):
        hm.unlink()
        heatmap_count += 1
    print(f"  Deleted {heatmap_count} old heatmaps (will be regenerated)")

    # ── Step 5: Clear FAISS index ─────────────────────────────────────────────
    for f in [_BACKEND / "faiss_index.bin", _BACKEND / "faiss_id_map.npy"]:
        if f.exists():
            f.unlink()
    print("  FAISS index cleared")

    # ── Step 6: Run batch inference on 40 real images ────────────────────────
    print()
    print("Running batch inference on 40 real images...")
    print("This will take ~7 minutes on CPU.")
    print()

    import subprocess
    result = subprocess.run(
        [sys.executable, str(_BACKEND / "batch_infer.py")],
        cwd=str(_BACKEND),
    )

    if result.returncode == 0:
        print()
        print("=" * 60)
        print("Done! Dataset trimmed to 40 real MIMIC-CXR cases.")
        print("Restart the backend to reload the new FAISS index.")
        print("=" * 60)
    else:
        print("Batch inference failed. Check output above.")
        sys.exit(1)


if __name__ == "__main__":
    main()
