-- =============================================================================
-- 003_phase5_auth_cleanup.sql — Reconcile RLS with the Phase 5 auth bridge
-- =============================================================================
-- Background
-- ----------
-- When the original RLS policies were written (schema.sql, 002_*.sql), we
-- assumed Supabase Auth would mint our application user IDs as auth.users.id.
-- In practice the two never matched: our users.id values were generated by
-- seed_demo_users.py (e.g. 4f9b9bc8-...) BEFORE any Supabase Auth account
-- existed; when Auth accounts were created later by seed_auth_users.py, they
-- got fresh, unrelated UUIDs (e.g. 6bccfff7-...). Phase 5 therefore bridges
-- the two layers by EMAIL, not by ID:
--
--   JWT (auth.users.email)  ──►  users.email  ──►  users.id (app-level)
--
-- Consequence: any RLS policy of the form  auth.uid() = some_users_fk  will
-- NEVER match for a real Supabase-Auth-issued JWT. Such a policy is dead
-- code and was harmless only because the FastAPI backend connects with the
-- service-role key (which bypasses RLS).
--
-- This migration rewrites those policies in terms of the email bridge so they
-- would actually work if a future client used the anon key + a signed-in JWT
-- to talk to PostgREST directly. Backend behaviour is unchanged because the
-- service role still bypasses every policy here.
--
-- Idempotent: every DROP / CREATE is guarded. Safe to re-run.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 0. Helper — bridge auth.email() → users.id for the active user
-- ---------------------------------------------------------------------------
-- Defined as STABLE so Postgres can cache the result within a single query.
-- SECURITY DEFINER lets the function read users without itself being subject
-- to RLS (otherwise the policies that depend on this would recurse). It only
-- ever returns the caller's OWN row — there is no parameter to pivot on, so
-- there's no privilege-escalation surface.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.app_user_id_for_session()
    RETURNS UUID
    LANGUAGE sql
    STABLE
    SECURITY DEFINER
    SET search_path = public
AS $$
    SELECT id
    FROM   users
    WHERE  email = auth.email()
      AND  status = 'active'
    LIMIT  1;
$$;

GRANT EXECUTE ON FUNCTION public.app_user_id_for_session() TO authenticated;


-- ---------------------------------------------------------------------------
-- 1. consultations — replace the dead auth.uid() = *_id policies
-- ---------------------------------------------------------------------------
-- OLD (dead code, never matches):
--   CREATE POLICY "doctor_update_consultation"     ON consultations FOR UPDATE
--     USING (auth.uid() = ward_doctor_id);
--   CREATE POLICY "radiologist_update_consultation" ON consultations FOR UPDATE
--     USING (auth.uid() = radiologist_id);
--
-- NEW: resolve the caller's app-level users.id via the email bridge, then
-- check it matches one of the two FK columns on the consultation row.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "doctor_update_consultation"     ON consultations;
DROP POLICY IF EXISTS "radiologist_update_consultation" ON consultations;

DO $$ BEGIN
    -- Single combined policy: caller is either the ward doctor OR the radiologist
    -- on this consultation. Cleaner than two parallel UPDATE policies whose
    -- effective union would be exactly this anyway.
    CREATE POLICY "participant_update_consultation"
        ON consultations
        FOR UPDATE
        USING (
            public.app_user_id_for_session() IN (ward_doctor_id, radiologist_id)
        );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ---------------------------------------------------------------------------
-- 2. users — let an authenticated user read their own row
-- ---------------------------------------------------------------------------
-- The service_only_users policy from 002_*.sql blocks all anon/authenticated
-- access (USING false). That is too strict once we have real auth: a client
-- using the anon key + a signed-in JWT must be able to look up its own role
-- to render the right UI without round-tripping through the FastAPI backend.
--
-- The policy below grants self-read only — never another user's row.
-- INSERT/UPDATE/DELETE remain service-role-only (no policy = no access for
-- non-service roles when RLS is enabled).
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "service_only_users" ON users;

DO $$ BEGIN
    CREATE POLICY "self_read_user"
        ON users
        FOR SELECT
        USING (email = auth.email());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ---------------------------------------------------------------------------
-- 3. audit_log — keep service-role-only, but make the intent explicit
-- ---------------------------------------------------------------------------
-- The audit log is a security-sensitive read: only system_admins should see
-- it, and that check happens in the FastAPI backend (require_role) before
-- any rows are returned. We deliberately do NOT add a self-read policy here:
-- a clinician should not see their own audit trail through the anon key,
-- because the backend's policy logic (e.g. redacting metadata) wouldn't run.
-- The blanket-deny is therefore correct; only the comment is updated.
-- ---------------------------------------------------------------------------
COMMENT ON POLICY "service_only_audit_log" ON audit_log IS
    'Service-role only. System-admin reads go through FastAPI /api/admin/audit-log '
    'where require_role enforces the access check before any row is fetched.';


-- ---------------------------------------------------------------------------
-- 4. Sanity check — list active policies after the migration
-- ---------------------------------------------------------------------------
-- Run this manually after applying to verify the rewrite landed cleanly:
--
--   SELECT schemaname, tablename, policyname, cmd, qual
--   FROM   pg_policies
--   WHERE  schemaname = 'public'
--   ORDER  BY tablename, policyname;
--
-- Expected (Phase 5):
--   patients      authenticated_read_patients      SELECT  auth.role() = 'authenticated'
--   cases         authenticated_read_cases         SELECT  auth.role() = 'authenticated'
--   predictions   authenticated_read_predictions   SELECT  auth.role() = 'authenticated'
--   consultations authenticated_read_consultations SELECT  auth.role() = 'authenticated'
--   consultations participant_update_consultation  UPDATE  app_user_id_for_session() IN (...)
--   users         self_read_user                   SELECT  email = auth.email()
--   audit_log     service_only_audit_log           ALL     false
-- ---------------------------------------------------------------------------
